#!/bin/bash
# vim: filetype=sh
sudo -Hiu postgres /usr/pgsql-9.5/bin/pg_dump django_comleave | gzip > /tmp/comleave.sql.gz
mv -f /tmp/comleave.sql.gz /home/tikhomirovsvl/
chown tikhomirovsvl /home/tikhomirovsvl/comleave.sql.gz
