#!/bin/bash
# vim: filetype=sh
bkpdir=/mnt/backup/comleave
date=`date +%Y-%m-%d`
datehour=`date +%Y-%m-%d__%H`     # file name for current dumps
mkdir -p ${bkpdir}/${date}
dumpdir=${bkpdir}/${date}         # directory name for today dumps
dbname=django_comleave
fname=${dbname}__${datehour}

PGPASSWORD='B070L<Mf4j9O15G' pg_dump -h 10.4.126.23 -p 5432 -U test ${dbname} | gzip > ${dumpdir}/${fname}.sql.gz 2> ${dumpdir}/${fname}.error
