* info
Compensatory leave
Отгулы/Переработки

front: Angular 2
back:  Django/flask(sqlalchemy)
db:    Postgresql

** Summary:
Есть люди (фио)
есть отгул\переработка(дата регистрации, дата и время отгула начала, срок в
мин(но ввод в получасах), статус-утвреждения, Комментарий)
роли (сотрудник, рук)

** View
формы / запросы:
регистрация
логин
просмотр зареганых
просмотр сотрудников
---просмотр сводки на текущий месяц
регистрация заявки отгула\переработки
просмотр заявок и редактирование, принятие
---
* Функционал
      человек фиксирует количество часов, которые он берет в отработку либо переработал
      руководитель либо акцептует, либо отменяет

      акцептованные значения считаются отгулы в минус, переработки в +
      !!при акцептовании должна быть возможность поправить заявленные часы
       и дальше разные выборки
       аутентификация логин/пароль + по LDAP потом прикрутить
       настраивалась отправка уведомления руководителю при поступлении новой заявки на фиксацию времени
      в часах, но с точностью до получаса
---
* Process
что делает angular?
представление выборок, на фронте.
шаблоны заменяем angular'ом
ангуля только дергает рест у джанги

** 1. make django app
** 2. make db, orm
** x. make views
** 3. angular2 app
** 4. views
+все отгулы, переработки, итог
+все запросы на отгул\пере
  редактирование:
+Добавление заявки. Выбор сотрудника(должно потом из сессии быть),
     ввод интервала в пределах получаса, тип 
     (дата, интервал-селект, комент-текст, переработкаЛи-Чек, персона-селект)
+отдельно рег отгула и отдельно переработки
    утвердить\отклонить
+все отказанные и возможность принять или обратно в зарег
+при акцептовании должна быть возможность поправить заявленные часы
      +Удалить
+все принятые и возможность отменить- обртано в зарег или отказать
+-Удобные даты
** 5. меню, навигация
** 6. аутентификация, роли, пользователи.
           но должна быть возможность добавить за другого?
     +login
     +logout
     +влияние прав и статуса логина
     +регистрация, добавление персоны.
     +Брать имя из логина(тогда надо переделать, либо использовать систеные джанги юзеров, либо хранить у персоны логин)

на фронт нельзя передвать инфу об auth. фронт легко хакнуть. значти надо
только ограничивать представления которые получают пользователи и админы?
и проверять статус в них

** TODO:
+можно тогда рест просто заменить json преобразованием 
+убрать рест(дсон). 

надо делать маленькие компоненты, выделить компоненты.
      1 msg done.
      2 auth component?
можно переписать регистрацию\логин в компоненты
Добавить сообщение об успешной\неуспешной регистрации
урлы бы вынести в приложение

написать тесты. 
+Уведомления на почту
без комента на проде не регается
коментрарии
рефакторинг
* New@19.05
+Вывести на 23 стенд SSH access need
+Переделать регистрацию на фронт(навигация)
  +и логин
  +и update
  +удалить старые методы на беке
+В регистрации нужно сообщение об успешной\неуспешной регистрации
+на странице регистрации переработки дату ставить по умолчанию текущий день
+и всегда в адекватном формате (разобраться с компонетом)
+добавить уведомление пользователю об принятии/отклонении заявления
+надо убрать возможность подать заявление без авторизации
+автостарт uwsgi(emperor mode)
+автоматически создавать manager user
+bootstrap grids
+енюшка с действиями над пользователем убегает за край экрана
+еще хорошо будет фильтры добавить. По пользователю, типу и периоду дат, для сводки, принятых и отклоненных
+переделать на gunicorn

* @24.05
Возможность восстановить пароль через почту или ldap?
systemd uwsgi setup on 10..23

learn bootstrap and use it
надо бы делать тестирование в дебаг режиме автоматом каждый раз!
сделать на сервер почты python -m smtpd -n -c DebuggingServer localhost:1025

надо бы сделать удаление пользователей
+приделать ldap
+напсать скриптик удаляющий всех
+если пароль вводить русским то не робит
улучшить (Не англ) почтовые уведомления
можно объединить регистрации в один компонент с типом заявки
?Проблема с длинными комментариями - портят всю разметку.
!подачу сделать либо черех пост либо экранировать комент
?возможность изменить заявку и даже тип?
* users test
+регИстрация (у тебя "зарегЕстрировать")
+Коментарий пишется - Комментарий
+надо локализовать: календарь, выбор периодов и т.д.
+отступ после нава
+надо подписать что с даты начала
? все сообщения бы в отдельном модуле.
? возможность редактировать не утвержденные заявки
?? одна дата - один отгул и одна переработка
+перенёс заголовок в кнопку
+-оформить огул и переработку другому сотруднику не должно быть
+ошибка в фильтре "по" . 25-25 пусто
+было бы удобно посмотреть только СВОЮ сводку за всё время
фильтр в сводке сразу не ставится в пользователя ибо он не успевает загрузиться.
срок в минутах переделать?.
понятные "Х часов У минут"
красивый адрес

** changelog 0.1
орфогрфические исправления.
запрет регистрации за других пользователей.
перенёс данные заголовка в кнопку.
локализовал компонент выбора даты.
** changelog 0.2
Исправил ошибку в фильтре даты.
Добавил фильтр сотрудника в сводку.
