# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overwork', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Overs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.DateTimeField(verbose_name='date registred')),
                ('start_date', models.DateTimeField(verbose_name='start date')),
                ('interval', models.IntegerField()),
                ('status', models.CharField(choices=[('R', 'Registred'), ('D', 'Denied'), ('A', 'Accepted')], default='R', max_length=100)),
                ('comment', models.CharField(max_length=512)),
            ],
        ),
    ]
