# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 09:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overwork', '0002_overs'),
    ]

    operations = [
        migrations.AddField(
            model_name='overs',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='overwork.Person'),
        ),
    ]
