# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overwork', '0004_auto_20170510_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='overs',
            name='is_over',
            field=models.BooleanField(default=True, verbose_name='is overwork?(else defect work)'),
            preserve_default=False,
        ),
    ]
