# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overwork', '0005_overs_is_over'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overs',
            name='is_over',
            field=models.BooleanField(verbose_name='is overwork?(else unworked)'),
        ),
    ]
