# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overwork', '0008_auto_20170511_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='login',
            field=models.CharField(default='no login', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='overs',
            name='interval',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='overs',
            name='is_over',
            field=models.BooleanField(default=False, verbose_name='is overwork?(else unworked)'),
        ),
    ]
