# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-16 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overwork', '0010_person_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='overs',
            name='kind',
            field=models.CharField(choices=[('O', 'Overwork/downwork'), ('I', 'Ill')], default='O', max_length=42),
        ),
    ]
